// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: hotel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelByIdRequest) Reset() {
	*x = GetHotelByIdRequest{}
	mi := &file_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelByIdRequest) ProtoMessage() {}

func (x *GetHotelByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelByIdRequest.ProtoReflect.Descriptor instead.
func (*GetHotelByIdRequest) Descriptor() ([]byte, []int) {
	return file_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHotelByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelByIdResponse) Reset() {
	*x = GetHotelByIdResponse{}
	mi := &file_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelByIdResponse) ProtoMessage() {}

func (x *GetHotelByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelByIdResponse.ProtoReflect.Descriptor instead.
func (*GetHotelByIdResponse) Descriptor() ([]byte, []int) {
	return file_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetHotelByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_hotel_proto protoreflect.FileDescriptor

const file_hotel_proto_rawDesc = "" +
	"\n" +
	"\vhotel.proto\x12\x05hotel\"%\n" +
	"\x13GetHotelByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x14GetHotelByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2W\n" +
	"\fHotelService\x12G\n" +
	"\fGetHotelById\x12\x1a.hotel.GetHotelByIdRequest\x1a\x1b.hotel.GetHotelByIdResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_hotel_proto_rawDescOnce sync.Once
	file_hotel_proto_rawDescData []byte
)

func file_hotel_proto_rawDescGZIP() []byte {
	file_hotel_proto_rawDescOnce.Do(func() {
		file_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_proto_rawDesc), len(file_hotel_proto_rawDesc)))
	})
	return file_hotel_proto_rawDescData
}

var file_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_proto_goTypes = []any{
	(*GetHotelByIdRequest)(nil),  // 0: hotel.GetHotelByIdRequest
	(*GetHotelByIdResponse)(nil), // 1: hotel.GetHotelByIdResponse
}
var file_hotel_proto_depIdxs = []int32{
	0, // 0: hotel.HotelService.GetHotelById:input_type -> hotel.GetHotelByIdRequest
	1, // 1: hotel.HotelService.GetHotelById:output_type -> hotel.GetHotelByIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotel_proto_init() }
func file_hotel_proto_init() {
	if File_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_proto_rawDesc), len(file_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotel_proto_goTypes,
		DependencyIndexes: file_hotel_proto_depIdxs,
		MessageInfos:      file_hotel_proto_msgTypes,
	}.Build()
	File_hotel_proto = out.File
	file_hotel_proto_goTypes = nil
	file_hotel_proto_depIdxs = nil
}
