// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PATH/hotel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserByIdResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelRequest) Reset() {
	*x = CreateHotelRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelRequest) ProtoMessage() {}

func (x *CreateHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelRequest.ProtoReflect.Descriptor instead.
func (*CreateHotelRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelResponse) Reset() {
	*x = CreateHotelResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelResponse) ProtoMessage() {}

func (x *CreateHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelResponse.ProtoReflect.Descriptor instead.
func (*CreateHotelResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHotelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// tutorial
type SimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *SimpleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *SimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_PATH_hotel_proto protoreflect.FileDescriptor

const file_PATH_hotel_proto_rawDesc = "" +
	"\n" +
	"\x10PATH/hotel.proto\x12\x05hotel\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x13GetUserByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"B\n" +
	"\x12CreateHotelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"%\n" +
	"\x13CreateHotelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rSimpleRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x0eSimpleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xad\x03\n" +
	"\fHotelService\x12E\n" +
	"\fGetHotelById\x12\x19.hotel.GetUserByIdRequest\x1a\x1a.hotel.GetUserByIdResponse\x12D\n" +
	"\vCreateHotel\x12\x19.hotel.CreateHotelRequest\x1a\x1a.hotel.CreateHotelResponse\x128\n" +
	"\tSimpleRpc\x12\x14.hotel.SimpleRequest\x1a\x15.hotel.SimpleResponse\x12C\n" +
	"\x12ServerStreamingRpc\x12\x14.hotel.SimpleRequest\x1a\x15.hotel.SimpleResponse0\x01\x12C\n" +
	"\x12ClientStreamingRpc\x12\x14.hotel.SimpleRequest\x1a\x15.hotel.SimpleResponse(\x01\x12L\n" +
	"\x19BidirectionalStreamingRpc\x12\x14.hotel.SimpleRequest\x1a\x15.hotel.SimpleResponse(\x010\x01B\x06Z\x04.;pbb\x06proto3"

var (
	file_PATH_hotel_proto_rawDescOnce sync.Once
	file_PATH_hotel_proto_rawDescData []byte
)

func file_PATH_hotel_proto_rawDescGZIP() []byte {
	file_PATH_hotel_proto_rawDescOnce.Do(func() {
		file_PATH_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)))
	})
	return file_PATH_hotel_proto_rawDescData
}

var file_PATH_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_PATH_hotel_proto_goTypes = []any{
	(*GetUserByIdRequest)(nil),  // 0: hotel.GetUserByIdRequest
	(*GetUserByIdResponse)(nil), // 1: hotel.GetUserByIdResponse
	(*CreateHotelRequest)(nil),  // 2: hotel.CreateHotelRequest
	(*CreateHotelResponse)(nil), // 3: hotel.CreateHotelResponse
	(*SimpleRequest)(nil),       // 4: hotel.SimpleRequest
	(*SimpleResponse)(nil),      // 5: hotel.SimpleResponse
}
var file_PATH_hotel_proto_depIdxs = []int32{
	0, // 0: hotel.HotelService.GetHotelById:input_type -> hotel.GetUserByIdRequest
	2, // 1: hotel.HotelService.CreateHotel:input_type -> hotel.CreateHotelRequest
	4, // 2: hotel.HotelService.SimpleRpc:input_type -> hotel.SimpleRequest
	4, // 3: hotel.HotelService.ServerStreamingRpc:input_type -> hotel.SimpleRequest
	4, // 4: hotel.HotelService.ClientStreamingRpc:input_type -> hotel.SimpleRequest
	4, // 5: hotel.HotelService.BidirectionalStreamingRpc:input_type -> hotel.SimpleRequest
	1, // 6: hotel.HotelService.GetHotelById:output_type -> hotel.GetUserByIdResponse
	3, // 7: hotel.HotelService.CreateHotel:output_type -> hotel.CreateHotelResponse
	5, // 8: hotel.HotelService.SimpleRpc:output_type -> hotel.SimpleResponse
	5, // 9: hotel.HotelService.ServerStreamingRpc:output_type -> hotel.SimpleResponse
	5, // 10: hotel.HotelService.ClientStreamingRpc:output_type -> hotel.SimpleResponse
	5, // 11: hotel.HotelService.BidirectionalStreamingRpc:output_type -> hotel.SimpleResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PATH_hotel_proto_init() }
func file_PATH_hotel_proto_init() {
	if File_PATH_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PATH_hotel_proto_goTypes,
		DependencyIndexes: file_PATH_hotel_proto_depIdxs,
		MessageInfos:      file_PATH_hotel_proto_msgTypes,
	}.Build()
	File_PATH_hotel_proto = out.File
	file_PATH_hotel_proto_goTypes = nil
	file_PATH_hotel_proto_depIdxs = nil
}
